import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* 구글 사이트 인증 메타 태그 */}
        <meta
          name="google-site-verification"
          content="vrjbXL35t1HQ8QP2B1PCdGiQRzKIiiU4Dx07LZYdhaA"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}

        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-Z1QR2SDFJV"
          strategy="afterInteractive"
        ></Script>
        <Script id="ga4-init" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-Z1QR2SDFJV');}
          `}
        </Script>
      </body>
    </html>
  );
}
